log:
  level: debug # trace, debug, info, warn, error, fatal
  std:
    enabled: true
  file:
    enabled: true
    path: path/to/log_dir/
middlewares:
  tcp: # todo
  tls: # todo
  http:
    redirect:
      - name: redirect-1
        uri: /new/path
        authority: new.host.to.go.com
        port: 8088
        scheme: http
        redirect_code: 301
    rewrite:
      - name: rewrite-1
        uri: /new/path
        authority: new.host.com
    timeout:
      - name: timeout-1
        write_request_timeout: 3000 # ms
        read_response_timout: 3000 # ms
    retries:
      - name: retries-1
        attempts: 3
        per_try_timeout: 100 # ms
        retry_on: # `AND`
          - 4XX
          - 5XX
          - TCP_ERROR
    fault:
      - name: fault-1
        delay:
          percentage: 0.5
          time: 100 # ms
        abort:
          percentage: 0.5
          http_status: 502
    mirror:
      - name: mirror-1
        destination:
          host: mirror.a.com
          port: 80
    header:
      - name: header-1
        request:
          - set:
              keyA: valueA
          - add:
              keyA: valueA-1
          - remove:
              - keyB
              - keyC
          - set:
              keyA: valueB
        response:
          - set:
              keyA: valueA
          - add:
              keyA: valueA-1
          - remove:
              - keyB
              - keyC
          - set:
              keyA: valueB
servers:
  - name: SERVER_A # optional, has default
    bind_address: 127.0.0.1 # optional, has default
    port: 8080
    protocol: https # tcp, tls, http, https
    timeout: # optional, has default
      read_timeout: 3000 # in ms, optional, has default
      write_timeout: 5000 # in ms, optional, has default
    tls: # optional, enabled only if protocol is `tls` or `https`
      mode: SIMPLE # or, MUTAL; optional, has default
      private_key: PRIVATE-KEY-CONTENT
      server_certificate: CERTIFICATE-CONTENT
      root_certificate: CERTIFICATE-CONTENT
      min_version: TLSV1_1
      max_version: TLS_AUTO
      https_redirect: true # enabled only if protocol is `https`
    hosts:
      - a.test.com
      - b.test.com
      - c.test.com
    services:
      - test-backend
services:
  - name: test-backend
    hosts:
      - a.test.com
      - b.test.com
    local: # optional
      path: /path/to/web/dir # optional
    tcp:
      - host: tcp.a.test.com
        port: 80
        weight: 25
      - host: tcp.b.test.com
        port: 88
        weight: 75
    tls:
      - match:
          - a.test.com
        route:
          - host: tls.a.test.com
        mode: SIMPLE # or MUTUAL, default SIMPLE

      - match:
          - b.test.com
          - c.test.com
        route:
          - host: tls.b.test.com
            weight: 50
          - host: tls.c.test.com
            weight: 50
    http:
      - match: # linked in `AND`
          - uri:
              exact: /index.html
              # prefix:
              # regex:
            scheme:
              exact: http
              # ...
            method:
              exact: get
            authority:
              exact: a.test.com
            headers:
              keyA:
                exact: valueA
              keyB:
                exact: valueB
            queries:
              queryA:
                exact: valueA
            ignore_case: true
        route:
          - host: http.a.test.com
            weight: 50
            middlewares:
              - redirect-1
              - rewrite-1
              - timeout-1
              - retries-1
              - fault-1
              - mirror-1
              - header-1
