servers:
  - address: 127.0.0.1
    port: 7777
    timeout: 5000
    use_ssl: false
    # private_key: path/to/private/key
    # certificate: path/to/certificate
    proxies:
      - entrances:
          - name: test
            host: test.com
            method: GET
            target: /
        # middleware:
        #   - name: middleware-1
        #     parameters: k1=v1,k2=v2
        backends:
          - name: httpbin
            host: httpbin.org
            port: 80
            timeout: 3000
            use_ssl: false
            # certificate: /path/to/certificate # use default cert
            method: GET
            target: /get
    log:
      to_std_out: true
      to_file: false
      log_filename: path/to/log
