servers:
  - name: SERVER_A # optional, has default
    bind_address: 127.0.0.1 # optional, has default
    port: 8080
    protocol: https # tcp, tls, http, https
    timeout: # optional, has default
      readRequestTimeout: 3000 # in ms, optional, has default
      writeResponseTimeout: 5000 # in ms, optional, has default
    tls: # optional, enabled only if protocol is `tls` or `https`
      mode: SIMPLE # or, MUTAL; optional, has default
      private_key: PRIVATE-KEY-CONTENT
      server_certificate: CERTIFICATE-CONTENT
      root_certificate: CERTIFICATE-CONTENT
      min_version: TLSV1_1
      max_version: TLS_AUTO
      httpsRedirect: true # enabled only if protocol is `https`
    hosts:
      - a.test.com
      - b.test.com
      - c.test.com
    backends:
      - test-backend
middlewares:
  tcp:  # todo
  tls:  # todo
  http:
    redirect:
      - name: redirect-1
        uri: /new/path
        authority: new.host.to.go.com
        port: 8088
        scheme: http
        redirectCode: 301
    rewrite:
      - name: rewrite-1
        uri: /new/path
        authority: new.host.com
    timeout:
      - name: timeout-1
        writeRequestTimeout: 3000 # ms
        readResponseTimout: 3000 # ms
    retries:
      - name: retries-1
        attempts: 3
        perTryTimeout: 100 # ms
        retryOn:  # `AND`
          - 4XX
          - 5XX
          - TCP_ERROR
    fault:
      - name: fault-1
        delay:
          percentage: 0.5
          time: 100 # ms
        abort:
          percentage: 0.5
          httpStatus: 502
    mirror:
      - name: mirror-1
        destination:
          - a.mirror.com
          - b.mirror.com
    header:
      - name: header-1
        request:
          - set:
              keyA: valueA
          - add:
              keyA: valueA-1
          - remove:
              - keyB
              - keyC
          - set:
              keyA: valueB
        response:
          - set:
              keyA: valueA
          - add:
              keyA: valueA-1
          - remove:
              - keyB
              - keyC
          - set:
              keyA: valueB
backends:
  - name: test-backend
    hosts:
      - a.test.com
      - b.test.com
    local: # optional
      path: /path/to/web/dir # optional
    tcp:
      - route:
          - destination: tcp.a.test.com
            weight: 25
          - destination: tcp.b.test.com
            weight: 75
    tls:
      - match:
          sniHosts:
            - a.test.com
        route:
          - destination: tls.a.test.com
      - match:
          sniHosts:
            - b.test.com
            - c.test.com
        route:
          - destination: tls.b.test.com
            weight: 50
          - destination: tls.c.test.com
            weight: 50
    http:
      - name: http-test-a
        match: # linked in `AND`
          - uri:
              exact: /index.html
              # prefix:
              # regex:
            scheme:
              exact: http
              # ...
            method:
              exact: get
            authority:
              exact: a.test.com
            headers:
              keyA:
                exact: valueA
              keyB:
                exact: valueB
            queries:
              queryA:
                exact: valueA
            ignoreCase: true
        route:
          - destination: http.a.test.com
            weight: 50
            middlewares:
              - redirect-1
              - rewrite-1
              - timeout-1
              - retries-1
              - fault-1
              - mirror-1
              - header-1
log:
  level: debug  # trace, debug, info, warn, error, fatal
  std:
    enabled: true
  file:
    enabled: true
    path: path/to/log_dir/
