log:
  level: debug # trace, debug, info, warn, error, fatal
  std:
    enabled: true
  file:
    enabled: true
    path: path/to/log_dir/
servers:
  - name: SERVER_A
    bind_address: 127.0.0.1
    port: 8080
    protocol: HTTP # TCP, TLS, HTTP, HTTP2, HTTP3
    timeout: # optional, has default
      read_timeout: 3000 # in ms, optional, has default
      write_timeout: 5000 # in ms, optional, has default
    hosts:
      - www.my-httpbin.org
    services:
      - httpbin
services:
  - name: httpbin
    hosts:
      - www.my-httpbin.org
      - www.my-httpbin2.org
    http:
      - match: # linked in `AND`
          - scheme:
              exact: http
        route:
          - host: httpbin.org
            port: 80
            weight: 100
